from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.enums import TA_RIGHT, TA_LEFT, TA_CENTER
from io import BytesIO
import qrcode
import hashlib
from datetime import datetime
from arabic_reshaper import reshape
from bidi.algorithm import get_display
import os

# RTL text helper for Arabic
def arabic_text(text):
    """Convert Arabic text to display format with proper RTL"""
    if not text:
        return ""
    try:
        reshaped_text = reshape(text)
        bidi_text = get_display(reshaped_text)
        return bidi_text
    except:
        return text

def generate_qr_code(data):
    """Generate QR code as image"""
    qr = qrcode.QRCode(version=1, box_size=10, border=4)
    qr.add_data(data)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")
    
    buffer = BytesIO()
    img.save(buffer, format='PNG')
    buffer.seek(0)
    return buffer

def generate_verification_hash(scan_id, target, timestamp):
    """Generate verification hash for report"""
    data = f"{scan_id}{target}{timestamp}"
    return hashlib.sha256(data.encode()).hexdigest()[:16]

def create_pdf_report(scan_data, language='en', translations=None):
    """
    Generate PDF report in specified language with proper RTL/LTR formatting
    
    Args:
        scan_data: Dictionary containing scan information
        language: 'en' or 'ar'
        translations: Dictionary of translated strings
    """
    buffer = BytesIO()
    
    # Page setup
    is_rtl = language == 'ar'
    doc = SimpleDocTemplate(buffer, pagesize=letter,
                           rightMargin=72, leftMargin=72,
                           topMargin=72, bottomMargin=18)
    
    # Content container
    story = []
    
    # Default translations
    if not translations:
        translations = {
            'reportTitle': 'Security Scan Report' if language == 'en' else 'تقرير فحص أمني',
            'scanDetails': 'Scan Details' if language == 'en' else 'تفاصيل الفحص',
            'scanId': 'Scan ID' if language == 'en' else 'معرف الفحص',
            'dateTime': 'Date & Time' if language == 'en' else 'التاريخ والوقت',
            'scanType': 'Scan Type' if language == 'en' else 'نوع الفحص',
            'target': 'Target' if language == 'en' else 'الهدف',
            'threatAssessment': 'Threat Assessment' if language == 'en' else 'تقييم التهديد',
            'riskLevel': 'Risk Level' if language == 'en' else 'مستوى المخاطر',
            'riskScore': 'Risk Score' if language == 'en' else 'درجة المخاطر',
            'confidence': 'Confidence' if language == 'en' else 'الثقة',
            'aiAnalysis': 'AI Threat Analysis' if language == 'en' else 'تحليل التهديد بالذكاء الاصطناعي',
            'recommendations': 'Security Recommendations' if language == 'en' else 'التوصيات الأمنية',
            'verificationInfo': 'Report Verification' if language == 'en' else 'التحقق من التقرير',
            'reportId': 'Report ID' if language == 'en' else 'معرف التقرير',
            'verificationHash': 'Verification Hash' if language == 'en' else 'رمز التحقق',
            'scanQR': 'Scan QR code to verify report authenticity' if language == 'en' else 'امسح رمز QR للتحقق من صحة التقرير',
            'generatedBy': 'Generated by' if language == 'en' else 'تم إنشاؤه بواسطة',
            'page': 'Page' if language == 'en' else 'صفحة',
            'Safe': 'Safe' if language == 'en' else 'آمن',
            'Suspicious': 'Suspicious' if language == 'en' else 'مشبوه',
            'Malicious': 'Malicious' if language == 'en' else 'ضار',
        }
    
    # Styles
    styles = getSampleStyleSheet()
    
    # Title style
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#00F0FF'),
        spaceAfter=30,
        alignment=TA_RIGHT if is_rtl else TA_LEFT,
    )
    
    # Heading style
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor=colors.HexColor('#00F0FF'),
        spaceAfter=12,
        alignment=TA_RIGHT if is_rtl else TA_LEFT,
    )
    
    # Normal text style
    normal_style = ParagraphStyle(
        'CustomNormal',
        parent=styles['Normal'],
        fontSize=11,
        alignment=TA_RIGHT if is_rtl else TA_LEFT,
    )
    
    # App Name Header
    app_name = "SecureVision AI"
    if is_rtl:
        story.append(Paragraph(arabic_text(app_name), title_style))
    else:
        story.append(Paragraph(app_name, title_style))
    
    # Report Title
    report_title = arabic_text(translations['reportTitle']) if is_rtl else translations['reportTitle']
    story.append(Paragraph(report_title, heading_style))
    story.append(Spacer(1, 20))
    
    # Scan Details Section
    details_title = arabic_text(translations['scanDetails']) if is_rtl else translations['scanDetails']
    story.append(Paragraph(details_title, heading_style))
    
    scan_info = [
        [arabic_text(translations['scanId']) if is_rtl else translations['scanId'], 
         scan_data.get('id', 'N/A')],
        [arabic_text(translations['dateTime']) if is_rtl else translations['dateTime'], 
         datetime.fromisoformat(scan_data.get('timestamp', datetime.now().isoformat())).strftime('%Y-%m-%d %H:%M:%S')],
        [arabic_text(translations['scanType']) if is_rtl else translations['scanType'], 
         scan_data.get('scan_type', 'N/A').upper()],
        [arabic_text(translations['target']) if is_rtl else translations['target'], 
         scan_data.get('target', 'N/A')],
    ]
    
    if is_rtl:
        scan_info = [[arabic_text(str(cell)) if isinstance(cell, str) and i == 0 else str(cell) 
                     for i, cell in enumerate(row[::-1])] for row in scan_info]
    
    scan_table = Table(scan_info, colWidths=[2*inch, 4*inch])
    scan_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#121214')),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#00F0FF')),
        ('TEXTCOLOR', (1, 0), (1, -1), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'RIGHT' if is_rtl else 'LEFT'),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#27272A'))
    ]))
    
    story.append(scan_table)
    story.append(Spacer(1, 20))
    
    # Threat Assessment
    threat_title = arabic_text(translations['threatAssessment']) if is_rtl else translations['threatAssessment']
    story.append(Paragraph(threat_title, heading_style))
    
    risk_level = scan_data.get('risk_level', 'Unknown')
    risk_level_translated = arabic_text(translations.get(risk_level, risk_level)) if is_rtl else translations.get(risk_level, risk_level)
    
    threat_info = [
        [arabic_text(translations['riskLevel']) if is_rtl else translations['riskLevel'], 
         risk_level_translated],
        [arabic_text(translations['riskScore']) if is_rtl else translations['riskScore'], 
         f"{scan_data.get('risk_score', 0):.1f}%"],
        [arabic_text(translations['confidence']) if is_rtl else translations['confidence'], 
         f"{scan_data.get('confidence', 0)*100:.0f}%"],
    ]
    
    if is_rtl:
        threat_info = [[row[1], row[0]] for row in threat_info]
    
    threat_table = Table(threat_info, colWidths=[2*inch, 4*inch])
    threat_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#121214')),
        ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#FFE600')),
        ('TEXTCOLOR', (1, 0), (1, -1), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'RIGHT' if is_rtl else 'LEFT'),
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, -1), 11),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#27272A'))
    ]))
    
    story.append(threat_table)
    story.append(Spacer(1, 20))
    
    # AI Analysis
    analysis_title = arabic_text(translations['aiAnalysis']) if is_rtl else translations['aiAnalysis']
    story.append(Paragraph(analysis_title, heading_style))
    
    explanation = scan_data.get('explanation', 'No analysis available')
    if is_rtl:
        explanation = arabic_text(explanation)
    
    story.append(Paragraph(explanation, normal_style))
    story.append(Spacer(1, 20))
    
    # Recommendations
    rec_title = arabic_text(translations['recommendations']) if is_rtl else translations['recommendations']
    story.append(Paragraph(rec_title, heading_style))
    
    recommendations = get_recommendations(scan_data.get('risk_level', 'Unknown'), language)
    for rec in recommendations:
        rec_text = arabic_text(f"• {rec}") if is_rtl else f"• {rec}"
        story.append(Paragraph(rec_text, normal_style))
        story.append(Spacer(1, 6))
    
    story.append(Spacer(1, 20))
    
    # Verification Section
    verify_title = arabic_text(translations['verificationInfo']) if is_rtl else translations['verificationInfo']
    story.append(Paragraph(verify_title, heading_style))
    
    # Generate verification hash
    verification_hash = generate_verification_hash(
        scan_data.get('id', ''), 
        scan_data.get('target', ''),
        scan_data.get('timestamp', '')
    )
    
    # QR Code
    qr_data = f"https://securevision.ai/verify/{scan_data.get('id', '')}"
    qr_buffer = generate_qr_code(qr_data)
    qr_img = Image(qr_buffer, width=1.5*inch, height=1.5*inch)
    
    verify_info = [
        [arabic_text(translations['reportId']) if is_rtl else translations['reportId'], 
         scan_data.get('id', 'N/A')[:16] + '...'],
        [arabic_text(translations['verificationHash']) if is_rtl else translations['verificationHash'], 
         verification_hash],
    ]
    
    if is_rtl:
        verify_info = [[row[1], row[0]] for row in verify_info]
    
    verify_table = Table(verify_info, colWidths=[2*inch, 4*inch])
    verify_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#121214')),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'RIGHT' if is_rtl else 'LEFT'),
        ('FONTNAME', (0, 0), (-1, -1), 'Courier'),
        ('FONTSIZE', (0, 0), (-1, -1), 9),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#27272A'))
    ]))
    
    story.append(verify_table)
    story.append(Spacer(1, 10))
    story.append(qr_img)
    
    qr_desc = arabic_text(translations['scanQR']) if is_rtl else translations['scanQR']
    story.append(Paragraph(qr_desc, normal_style))
    
    # Build PDF
    doc.build(story)
    
    buffer.seek(0)
    return buffer

def get_recommendations(risk_level, language='en'):
    """Get security recommendations based on risk level"""
    recommendations_en = {
        'Safe': [
            'Continue monitoring this target regularly',
            'Maintain current security protocols',
            'Keep security software up to date',
        ],
        'Suspicious': [
            'Exercise caution when interacting with this target',
            'Verify authenticity through alternative channels',
            'Enable additional security monitoring',
            'Consider blocking if suspicious activity persists',
        ],
        'Malicious': [
            'DO NOT interact with this target',
            'Block access immediately',
            'Report to security team',
            'Scan all systems that may have been exposed',
            'Change credentials if any were shared',
        ]
    }
    
    recommendations_ar = {
        'Safe': [
            'استمر في مراقبة هذا الهدف بانتظام',
            'حافظ على بروتوكولات الأمان الحالية',
            'حافظ على تحديث برامج الأمان',
        ],
        'Suspicious': [
            'توخ الحذر عند التفاعل مع هذا الهدف',
            'تحقق من الأصالة عبر قنوات بديلة',
            'قم بتفعيل مراقبة أمنية إضافية',
            'فكر في الحظر إذا استمر النشاط المشبوه',
        ],
        'Malicious': [
            'لا تتفاعل مع هذا الهدف',
            'احظر الوصول فوراً',
            'أبلغ فريق الأمن',
            'افحص جميع الأنظمة التي قد تكون معرضة',
            'غير بيانات الاعتماد إذا تم مشاركتها',
        ]
    }
    
    recs = recommendations_ar if language == 'ar' else recommendations_en
    return recs.get(risk_level, recs.get('Suspicious', []))
